

#收件人，可以是一个列表
reciver: 'isshitao@163.com'

#发件人
sender_mail: '1950883679@qq.com'

#qq邮箱授权码
sender_pass: 'qsqyyailafjibdia'

#邮件头尾信息
msg_root_From: '测试——CI自动化API部署测试机<1950883679@qq.com>'

#邮件主题title
subject: '16点01分巡检发现异常'

#邮件文本内容
text_info: '异常请查收'

#邮件超文本
url: 'https://test-shop.hmhyg.com/attestation'
html_info:  '<p><a href="%s">click me</a></p>
            <p>i am very galsses for you</p>'


#邮件图片
image_path: 'C:\Users\Administrator\Desktop\a0c2e9c0471a8161e77de082501c1ba.png'

#邮件附件
txt_file_path : 'C:\Users\Administrator\Desktop\test_email.txt'




