# —— 以下为SSH方式连接的mysql配置，只能保留一组，另一组必须用#号每行注释掉（变成绿色）

mysql_test:

  sql_adress: '172.17.87.195'
  sql_port: 53306
  sql_username: 'root'
  sql_password: 'GIChain123@2020m2C'
  sql_db: 'hygtest'

'''
外网IP: 8.140.131.131改为 47.95.8.160
内网： 172.17.87.195
端口:53306
用户名： root
密码： GIChain123@2020m2C'''